export enum CommonFailureReason {
  // Common
  INVALID_SIGNATURE = "INVALID_SIGNATURE",
  MISSING_REFUND_OPTIONS = "MISSING_REFUND_OPTIONS",
  NON_MATCHING_TRANSACTION = "NON_MATCHING_TRANSACTION",
  UNSUPPORTED_CHAIN = "UNSUPPORTED_CHAIN",
  WRONG_VM_TYPE = "WRONG_VM_TYPE",

  // Input
  INVALID_INPUT = "INVALID_INPUT",

  // Output
  INSUFFICIENT_OUTPUT_AMOUNT = "INSUFFICIENT_OUTPUT_AMOUNT",
  INVALID_OUTPUT_CALL = "INVALID_OUTPUT_CALL",
  OUTPUT_CALLS_NOT_EXECUTED = "OUTPUT_CALLS_NOT_EXECUTED",
}
